### ISSUE TITLE
Sir I want to subscribe to your service!! 

### ISSUE THREAD

**Issue by SP-XD** [AP-XD/AP-Broadband#1]
I liked your packages. They are cheap compared to other providers and seams reliable so I want to subscribe to your service!!  Pls respond 😜

**Comment by AP-XD** [comment]
I'm sorry but the plans shown here are only for description purposes.
Service unavailable 404😂

**Comment by SP-XD** [comment]
feeling sad with 39+30 others, but still thanks sir for the super fast customer support 😜
